# Generated by Django 4.1.4 on 2022-12-25 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_donateuruser_updated_at_effectuerdonarge_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateuruser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 15, 18, 16, 341288, tzinfo=datetime.timezone.utc), verbose_name='last_login'),
        ),
    ]
